Wings: FIx stoplogic
pelican-dev/wings pull request #31
Opened 2024-06-16 09:03 UTC by QuintenQVD0

# Changes

- Instead of  ContainerKill we use ContainerStop
- This takes 3 args, the ctx, the container id and the container.StopOptions what takes a timeout and a signal as a string

The signal must be a string so "SIGTERM" but we used to pass to syscall.SIGTERM and trim some parts but that does not work.
so in the function, all incoming signals are converted to signals in string format. They also get matched with their corresponding timeout. What means for any signal the default timeout before it gets killed is 10 seconds. So:
1. The container gets the signal 
2. it sends the signal to the container
3. if it exitis in those 10 seconds then it will just continue
4. if not after 10 seconds, SIGKILL is sent

The timeout is 0 for os.kill as that is what the kill button sends and then it should stop immediately  

this is combined with my panel PR so `^C` send SIGTERM

This also makes wine eggs not need anymore for `^^C` but wine can not wait it will just direct exit (how it also does it with `^^C`)

you can also now do as stop `^SIGINT`, `^SIGTERM`, `^SIGABRT` what will be converted in to a signal

## Example 

### mordhau:

![afbeelding](https://github.com/pelican-dev/wings/assets/67589015/47cc8811-8fe5-41f1-8e33-28af6e1e17ef)

### Nodejs
![afbeelding](https://github.com/pelican-dev/wings/assets/67589015/d56dc4e5-12dd-4998-997f-3238b3b7938f)
![afbeelding](https://github.com/pelican-dev/wings/assets/67589015/0293d554-37a6-4821-8c24-38f199e06c76)

2024-06-16 09:30 UTC, RMartinOscar commented on environment/docker/power.go
> +	case os.Kill:
```suggestion
```

2024-06-16 09:31 UTC, RMartinOscar commented on environment/docker/power.go
> +		sig = "SIGKILL"
```suggestion
```

2024-06-16 09:31 UTC, RMartinOscar commented on environment/docker/power.go
> +		noWaitTimeout = 0
```suggestion
```

2024-06-16 09:59 UTC, RMartinOscar commented on environment/docker/power.go
> +	case os.Kill:
```suggestion

```

2024-06-16 10:00 UTC, RMartinOscar commented on environment/docker/power.go
> +		sig = "SIGKILL"
```suggestion

```

2024-06-16 10:00 UTC, RMartinOscar commented on environment/docker/power.go
> +		noWaitTimeout = 0
```suggestion
```

2024-06-16 10:01 UTC, RMartinOscar requested changes
```suggestion
	case os.Kill:
		sig = "SIGKILL"
		noWaitTimeout = 0
```
Those are useles because of the default case

2024-06-16 10:02 UTC, QuintenQVD0 commented
the docker default is SIGTERM and a timeout of 10seconds? and sigkill must happen imiditaly ?

2024-06-16 10:07 UTC, RMartinOscar commented
There's no use to match case for os.Kill when the consequence is the same as the default case

2024-06-16 10:08 UTC, QuintenQVD0 commented
> There's no use to match case for os.Kill when the consequence is the same as the default case

I changed it.

2024-06-16 11:01 UTC, QuintenQVD0 commented
Converted to a draft as their is something wrong with the wings or panel logic itself

2024-07-01 16:24 UTC, QuintenQVD0 commented
IF you revert the this commit: https://github.com/pelican-dev/wings/commit/7bf9f6a9d0f8061bcdbcceeb34372d0f32ad25e6

then stop works but kill is broken

2024-07-01 21:25 UTC, RMartinOscar commented
[This](https://github.com/pterodactyl/wings/pull/192) may resolve it

2024-07-01 22:19 UTC, QuintenQVD0 commented
> [This](https://github.com/pterodactyl/wings/pull/192) may resolve it

I worked with him and no. Their is something weong with our panel reporting container statuses. I can't realy point to what exactly but this pr does the same just a diffrend way.

2024-07-30 16:59 UTC, notAreYouScared commented
@QuintenQVD0 Any update with this?

2024-07-30 17:04 UTC, QuintenQVD0 commented
> @QuintenQVD0 Any update with this?
> 

I have been working a lot latly so my time is limited. The logic is right but there something else preventing this to work with the state of the container.  (most servers in pelican even on properly stop mark it as crashed) that it is skipping the stopping state and so it thinks it has crashed. So until that is fixt this should not be merged as then a server can not be stoped anymore.

 Something is or went wrong with eather a panel update or the pr of Kubi to signal the panel of a state changes.

2024-09-07 18:39 UTC, QuintenQVD0 commented
Moral of this PR.

Fix the broken stop logic for signals (if https://github.com/pelican-dev/panel/pull/407 is also merged ofc)
Fix the crash detection issue because of a pending api call to the panel that had to finish before the crash detection could running causing it not to see the server go thru the stopping state.

2024-10-21 18:32 UTC, parkervcp requested changes

2024-10-21 18:32 UTC, parkervcp commented on environment/docker/power.go
> +		signal := "SIGKILL"
This could be moved into the switch as the default case

2024-10-22 19:44 UTC, parkervcp approved these changes
LGTM

2024-10-26 23:21 UTC, merged